// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {PluginType} from "./PluginType";

export interface Plugin {
    plugin_type: PluginType,
    name: string,
    vendor: string | null,
    path_to_file: string,
}